// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace MarkdownModuleCssNamespace {
    export interface IMarkdownModuleCss {
        root: string;
    }
}

declare const MarkdownModuleCssModule: MarkdownModuleCssNamespace.IMarkdownModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: MarkdownModuleCssNamespace.IMarkdownModuleCss;
};

export = MarkdownModuleCssModule;
