const path = require('path');
const webpack = require('webpack');
const CopyPlugin = require('copy-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const EsmWebpackPlugin = require('@purtuga/esm-webpack-plugin');
const glob = require('glob');
const jsdoc2md = require('jsdoc-to-markdown');

const staticFiles = [
    { from: './src/index.html' },
    { from: './src/iframe/*.html', to: '[name].[ext]' },
    { from: './public/assets', to: 'assets' },
    {
        from: 'node_modules/jstree/dist/jstree.min.js',
        to: 'jstree/jstree.min.js',
    },
    {
        from: 'node_modules/jstree/dist/themes/default/style.min.css',
        to: 'jstree/jstree.min.css',
    },
    {
        from: 'node_modules/jstree/dist/themes/default/32px.png',
        to: 'jstree/32px.png',
    },
    {
        from: 'node_modules/jstree/dist/themes/default/throbber.gif',
        to: 'jstree/throbber.gif',
    },
    {
        from: 'node_modules/jquery/dist/jquery.min.js',
        to: 'jstree/jquery.min.js',
    },
    { from: 'node_modules/@tensorflow/tfjs-core/dist/' },
];

const alias = {
    '@src': path.join(__dirname, 'src'),
    '@store': path.join(__dirname, 'src/store'),
    '@doc': path.join(__dirname, 'src/doc'),
    '@localdb': path.join(__dirname, 'src/localdb'),
    '@util': path.join(__dirname, 'src/util'),
    '@lib': path.join(__dirname, 'src/lib'),
    '@sandbox': path.join(__dirname, 'src/sandbox'),
    '@shared-styles': path.join(__dirname, 'src/components/shared-styles.css'),
    '@components': path.join(__dirname, 'src/components'),
    '@worker': path.join(__dirname, 'src/worker'),
    '@modal': path.join(__dirname, 'src/components/modal'),
    '@elements': path.join(__dirname, 'src/components/elements'),
    '@pages': path.join(__dirname, 'src/components/pages'),
    '@scenario': path.join(__dirname, 'src/scenario'),

    node_modules: path.join(__dirname, 'node_modules'),
};

module.exports = {
    entry: {
        // 'app': './src/component/ai-app',
        app: './src/index.tsx',
        'scenario-worker': './src/worker/scenario-worker',
        monaco: './src/iframe/monaco',
        jstree: './src/iframe/jstree',
        'monaco/editor-worker': 'monaco-editor/esm/vs/editor/editor.worker',
        'monaco/json-worker': 'monaco-editor/esm/vs/language/json/json.worker',
        'monaco/ts-worker':
            'monaco-editor/esm/vs/language/typescript/ts.worker',
        'lib/utils': './src/lib/utils',
        'lib/prolog': './src/lib/prolog',
        'lib/tensorflow': './src/lib/tensorflow',
    },

    output: {
        filename: '[name].js',
        library: 'LIB',
        libraryTarget: 'var',
    },

    resolve: {
        alias,
        extensions: ['.ts', '.js', '.mjs', '.tsx', '.jsx'],
    },

    module: {
        rules: [
            {
                test: /\.(ts|js|mjs)x?$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                },
            },
            {
                test: /\.(js|pl|md|json)$/,
                include: path.join(__dirname, 'src/scenario/'),
                use: [
                    {
                        loader: 'raw-loader',
                    },
                ],
            },
            {
                test: /\.(png|jpg|gif)$/,
                include: path.join(__dirname, 'src/scenario/'),
                use: [
                    {
                        loader: 'url-loader',
                    },
                ],
            },
            {
                test: /\.css$/,
                include: /node_modules/,
                loader: ['style-loader', 'css-loader'],
            },
            {
                test: /\.css$/,
                include: path.join(__dirname, 'src/'),
                loader: [
                    'style-loader',
                    {
                        loader: '@teamsupercell/typings-for-css-modules-loader',
                        options: {
                            banner:
                                '// autogenerated by typings-for-css-modules-loader.\n// Do not change this file manually!\n',
                        },
                    },
                    {
                        loader: 'css-loader',
                        options: { modules: true },
                    },
                ],
            },
            {
                test: /\.(jpe?g|png|gif|svg|ttf)$/i,
                exclude: path.join(__dirname, 'src/scenario/'),
                loader: 'file-loader',
                options: {
                    name: '/assets/[name].[ext]',
                },
            },
        ],
    },

    plugins: [
        new CopyPlugin(staticFiles),
        // new HtmlWebpackPlugin({
        //     template: 'src/index.ejs',
        //     chunks: ['app'],
        // }),
        new FaviconsWebpackPlugin({
            logo: './public/assets/logo.png',
            cache: true,
            //publicPath: '/',
            inject: true,
            favicons: {
                appName: 'AI Coding4Fun',
                appDescription: 'AI programming framework',
                developerURL: null, // prevent retrieving from the nearest package.json
                background: '#fff',
                theme_color: '#f83',
                icons: {
                    android: false,
                    appleIcon: false,
                    appleStartup: false,
                    coast: false,
                    yandex: false,
                },
            },
        }),
        new EsmWebpackPlugin({
            exclude(fileName, chunck) {
                // exclude all non library files
                return !/^lib\/.+.\.js$/i.test(fileName);
            },
        }),
    ],

    devServer: {
        watchContentBase: true,
        compress: true,
        port: 9000,
        publicPath: '/',
        historyApiFallback: true,
        disableHostCheck: true,
        stats: {
            children: false,
            maxModules: 0,
        },
        clientLogLevel: 'warning',
    },
};
