// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace NewsModuleCssNamespace {
    export interface INewsModuleCss {
        root: string;
    }
}

declare const NewsModuleCssModule: NewsModuleCssNamespace.INewsModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: NewsModuleCssNamespace.INewsModuleCss;
};

export = NewsModuleCssModule;
