// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace GlobalStyleCssNamespace {
  export interface IGlobalStyleCss {
    error: string;
    no: string;
    ok: string;
    warning: string;
    yes: string;
  }
}

declare const GlobalStyleCssModule: GlobalStyleCssNamespace.IGlobalStyleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GlobalStyleCssNamespace.IGlobalStyleCss;
};

export = GlobalStyleCssModule;
