// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace ProjectIndexModuleCssNamespace {
  export interface IProjectIndexModuleCss {
    project: string;
    projectList: string;
  }
}

declare const ProjectIndexModuleCssModule: ProjectIndexModuleCssNamespace.IProjectIndexModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ProjectIndexModuleCssNamespace.IProjectIndexModuleCss;
};

export = ProjectIndexModuleCssModule;
