// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace C4FModalCssNamespace {
  export interface IC4FModalCss {
    background: string;
    content: string;
    modal: string;
    no: string;
    yes: string;
  }
}

declare const C4FModalCssModule: C4FModalCssNamespace.IC4FModalCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: C4FModalCssNamespace.IC4FModalCss;
};

export = C4FModalCssModule;
