// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace FileTreeCssNamespace {
    export interface IFileTreeCss {
        delete: string;
        files: string;
        filetree: string;
        folders: string;
        icon: string;
    }
}

declare const FileTreeCssModule: FileTreeCssNamespace.IFileTreeCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FileTreeCssNamespace.IFileTreeCss;
};

export = FileTreeCssModule;
