// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace ConsoleModuleCssNamespace {
    export interface IConsoleModuleCss {
        root: string;
    }
}

declare const ConsoleModuleCssModule: ConsoleModuleCssNamespace.IConsoleModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ConsoleModuleCssNamespace.IConsoleModuleCss;
};

export = ConsoleModuleCssModule;
