// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace WelcomeModuleCssNamespace {
    export interface IWelcomeModuleCss {
        check: string;
        root: string;
    }
}

declare const WelcomeModuleCssModule: WelcomeModuleCssNamespace.IWelcomeModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: WelcomeModuleCssNamespace.IWelcomeModuleCss;
};

export = WelcomeModuleCssModule;
