// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace HeaderModuleCssNamespace {
  export interface IHeaderModuleCss {
    breadcrumb: string;
    logo: string;
    navbar: string;
  }
}

declare const HeaderModuleCssModule: HeaderModuleCssNamespace.IHeaderModuleCss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HeaderModuleCssNamespace.IHeaderModuleCss;
};

export = HeaderModuleCssModule;
