// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace ImpressumModuleCssNamespace {
    export interface IImpressumModuleCss {
        root: string;
    }
}

declare const ImpressumModuleCssModule: ImpressumModuleCssNamespace.IImpressumModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ImpressumModuleCssNamespace.IImpressumModuleCss;
};

export = ImpressumModuleCssModule;
