// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace FileViewerModuleCssNamespace {
    export interface IFileViewerModuleCss {
        image: string;
        root: string;
        tabs: string;
    }
}

declare const FileViewerModuleCssModule: FileViewerModuleCssNamespace.IFileViewerModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FileViewerModuleCssNamespace.IFileViewerModuleCss;
};

export = FileViewerModuleCssModule;
