// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace FileTreeModuleCssNamespace {
    export interface IFileTreeModuleCss {
        contextMenu: string;
        fileTree: string;
    }
}

declare const FileTreeModuleCssModule: FileTreeModuleCssNamespace.IFileTreeModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FileTreeModuleCssNamespace.IFileTreeModuleCss;
};

export = FileTreeModuleCssModule;
