// autogenerated by typings-for-css-modules-loader.
// Do not change this file manually!

declare namespace ProjectModuleCssNamespace {
    export interface IProjectModuleCss {
        horizontal: string;
        loading: string;
        pane: string;
        root: string;
        tabs: string;
        vertical: string;
    }
}

declare const ProjectModuleCssModule: ProjectModuleCssNamespace.IProjectModuleCss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ProjectModuleCssNamespace.IProjectModuleCss;
};

export = ProjectModuleCssModule;
